/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_SystemProcess */

#ifndef _Included_utils_SystemProcess
#define _Included_utils_SystemProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_SystemProcess
 * Method:    systemCall
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_utils_SystemProcess_systemCall
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
